/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiKeyNotification: typeof import('./components/ApiKeyNotification.vue')['default']
    ApiKeyUpdateDialog: typeof import('./components/ApiKeyUpdateDialog.vue')['default']
    AppLayout: typeof import('./components/AppLayout.vue')['default']
    BalanceCard: typeof import('./components/BalanceCard.vue')['default']
    CountUp: typeof import('./components/CountUp.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    FloatModelCard: typeof import('./components/FloatModelCard.vue')['default']
    GlassMonthPicker: typeof import('./components/GlassMonthPicker.vue')['default']
    GlassSelect: typeof import('./components/GlassSelect.vue')['default']
    GlowBorder: typeof import('./components/GlowBorder.vue')['default']
    IconButton: typeof import('./components/IconButton.vue')['default']
    LoginButton: typeof import('./components/LoginButton.vue')['default']
    LoginNotification: typeof import('./components/LoginNotification.vue')['default']
    ParticleBg: typeof import('./components/ParticleBg.vue')['default']
    PercentBar: typeof import('./components/PercentBar.vue')['default']
    Popover: typeof import('./components/Popover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleGroup: typeof import('./components/ToggleGroup.vue')['default']
    TokenRing: typeof import('./components/TokenRing.vue')['default']
  }
}
